VIA_ENABLE = yes
VIAL_ENABLE = yes
RAW_ENABLE = yes
DYNAMIC_KEYMAP_ENABLE = yes
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = ws2812
RGB_MATRIX_CUSTOM_KB = yes
WS2812_DRIVER = pwm
VIALRGB_ENABLE = yes

DYNAMIC_KEYMAP_LAYER_COUNT = 11
OPT_DEFS += -DDYNAMIC_KEYMAP_LAYER_COUNT=$(DYNAMIC_KEYMAP_LAYER_COUNT) -DVIA_EEPROM_CUSTOM_CONFIG_SIZE=145

COMBO_ENABLE = no
QMK_SETTINGS = no
TAP_DANCE_ENABLE = yes
KEY_OVERRIDE_ENABLE = no
CONSOLE_ENABLE = no
NKRO_ENABLE = no

REPEAT_KEY_ENABLE = no
CAPS_WORD_ENABLE = no
MAGIC_ENABLE = no
LAYER_LOCK_ENABLE = no
GRAVE_ESC_ENABLE = no
SPACE_CADET_ENABLE = no
